title: KylanRobinson.com
description: Personal site of Kylan Robinson

minima:

  social_links:
    twitter: kylan
    github: kylan
    instagram: kylanrobinson
    linkedin: kylanrobinson
    telegram: kylanrobinson
    keybase: kylanrobinson

header_pages:
  - index.md
  - posts.md
  - cv.md
  - patents.md
  - recommendations.md

theme: minima

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag

sass:
  style: compressed

include: [".well-known"]
