title: KylanRobinson.com

author: Kylan Robinson
email: me@kylanrobinson.com

twitter_username: kylan
github_username: kylan
instagram_username: kylanrobinson
linkedin_username: kylanrobinson
telegram_username: kylanrobinson
keybase_username: kylanrobinson

header_pages:
  - index.md
  - posts.md
  - cv.md
  - patents.md
  - recommendations.md

remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jemoji
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag

sass:
  style: compressed

include: [".well-known"]
