theme: minima
title: KylanRobinson.com
description: Personal site of Kylan Robinson
social-network-links:
  rss: true
  email: "kylan@kylanrobinson.com"
  github: kylan
  twitter: kylan
  instagram: kylanrobinson
  linkedin: kylanrobinson
sass:
  sass_dir: _sass
  style: compressed
