theme: minima
title: KylanRobinson.com
description: Personal site of Kylan Robinson
social-network-links:
  rss: true
  email: "kylan@kylanrobinson.com"
  github: kylan
  twitter: kylan
  instagram: kylanrobinson
  linkedin: kylanrobinson
sass:
  style: compressed
header_pages:
  - index.md
  - posts.md
  - cv.md
  - patents.md
  - recommendations.md
plugins:
  - jemoji
include: [".well-known"]
