theme: minima
title: KylanRobinson.com
description: Personal site of Kylan Robinson
sass:
  style: compressed
header_pages:
  - index.md
  - posts.md
  - cv.md
  - patents.md
  - recommendations.md
plugins:
  - jemoji
  - jekyll-feed
  - jekyll-seo-tag
include: [".well-known"]

minima:
  social_links:
    twitter: kylan
    github: kylan
    instagram: kylanrobinson
    linkedin: kylanrobinson
    keybase: kylanrobinson
    telegram: kylanrobinson